services:
  db-postgres:
    container_name: postgres17
    hostname: postgres17
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: "Asia/Seoul"  # 타임존 설정
    volumes:
      - ${DATA_PATH}:/var/lib/postgresql/data
      - ${LOG_PATH}:/var/lib/postgresql/logs
    networks:
      - shared-network

  app-backend:
    container_name: backend
    image: discphy/hhplus:backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ="Asia/Seoul"  # 타임존 설정
    deploy:
      resources:
        limits:
          memory: 1g  # 메모리 제한
    depends_on:
      - db-postgres
    networks:
      - shared-network
      
networks:
  shared-network: