openapi: 3.0.1
info:
  title: hhplus-precourse API
  description: 향해플러스 사전스터디 API 문서
  version: 1.0.0
servers:
- url: localhost:8080
tags: []
paths:
  /posts:
    get:
      tags:
      - 게시글
      summary: "게시글 : 목록 조회"
      description: "게시글 : 목록 조회"
      operationId: GetPostListControllerTest
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/posts2009334939'
              examples:
                GetPostListControllerTest:
                  value: |-
                    {
                      "status" : "SUCCESS",
                      "message" : "성공",
                      "data" : [ {
                        "id" : 1,
                        "title" : "제목",
                        "author" : "작성자명",
                        "content" : "내용",
                        "createdAt" : "2025-02-24T00:01:09.539027",
                        "updatedAt" : "2025-02-24T00:01:09.53907"
                      } ]
                    }
    post:
      tags:
      - 게시글
      summary: "게시글 : 생성"
      description: "게시글 : 생성"
      operationId: CreatePostControllerTest
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/posts-1896447963'
            examples:
              CreatePostControllerTest:
                value: |-
                  {
                    "author" : "작성자명",
                    "title" : "제목",
                    "content" : "내용",
                    "password" : "비밀번호"
                  }
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/posts-id-1467773512'
              examples:
                CreatePostControllerTest:
                  value: |-
                    {
                      "status" : "SUCCESS",
                      "message" : "성공",
                      "data" : {
                        "id" : 1,
                        "title" : "제목",
                        "author" : "작성자명",
                        "content" : "내용",
                        "createdAt" : "2025-02-24T00:01:06.630963",
                        "updatedAt" : "2025-02-24T00:01:06.630973"
                      }
                    }
  /posts/{id}:
    get:
      tags:
      - 게시글
      summary: "게시글 : 조회"
      description: "게시글 : 조회"
      operationId: GetPostControllerTest
      parameters:
      - name: id
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/posts-id-1467773512'
              examples:
                GetPostControllerTest:
                  value: |-
                    {
                      "status" : "SUCCESS",
                      "message" : "성공",
                      "data" : {
                        "id" : 1,
                        "title" : "제목",
                        "author" : "작성자명",
                        "content" : "내용",
                        "createdAt" : "2025-02-24T00:01:08.953953",
                        "updatedAt" : "2025-02-24T00:01:08.953958"
                      }
                    }
    put:
      tags:
      - 게시글
      summary: "게시글 : 수정"
      description: "게시글 : 수정"
      operationId: UpdatePostControllerTest
      parameters:
      - name: id
        in: path
        description: ""
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/posts-id-1965008156'
            examples:
              UpdatePostControllerTest:
                value: |-
                  {
                    "author" : "수정할 작성자명",
                    "title" : "수정할 제목",
                    "content" : "수정할 내용",
                    "password" : "비밀번호"
                  }
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/posts-id-1467773512'
              examples:
                UpdatePostControllerTest:
                  value: |-
                    {
                      "status" : "SUCCESS",
                      "message" : "성공",
                      "data" : {
                        "id" : 1,
                        "title" : "제목",
                        "author" : "작성자명",
                        "content" : "내용",
                        "createdAt" : "2025-02-24T00:01:10.07509",
                        "updatedAt" : "2025-02-24T00:01:10.0751"
                      }
                    }
    delete:
      tags:
      - 게시글
      summary: "게시글 : 삭제"
      description: "게시글 : 삭제"
      operationId: DeletePostControllerTest
      parameters:
      - name: id
        in: path
        description: ""
        required: true
        schema:
          type: string
      - name: password
        in: query
        description: 비밀번호
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/posts-id1564421643'
              examples:
                DeletePostControllerTest:
                  value: |-
                    {
                      "status" : "SUCCESS",
                      "message" : "성공",
                      "data" : null
                    }
components:
  schemas:
    posts-1896447963:
      required:
      - author
      - content
      - password
      - title
      type: object
      properties:
        password:
          type: string
          description: 비밀번호
        author:
          type: string
          description: 작성자명
        title:
          type: string
          description: 제목
        content:
          type: string
          description: 내용
    posts-id-1965008156:
      required:
      - author
      - content
      - password
      - title
      type: object
      properties:
        password:
          type: string
          description: 비밀번호
        author:
          type: string
          description: 수정할 작성자명
        title:
          type: string
          description: 수정할 제목
        content:
          type: string
          description: 수정할 내용
    posts-id1564421643:
      required:
      - data
      - message
      - status
      type: object
      properties:
        message:
          type: string
          description: 메시지
        status:
          type: string
          description: 결과 상태
    posts-id-1467773512:
      required:
      - data
      - message
      - status
      type: object
      properties:
        data:
          required:
          - author
          - content
          - createdAt
          - id
          - title
          - updatedAt
          type: object
          properties:
            createdAt:
              type: string
              description: 생성일시
            author:
              type: string
              description: 작성자명
            id:
              type: number
              description: 게시글 ID
            title:
              type: string
              description: 제목
            content:
              type: string
              description: 내용
            updatedAt:
              type: string
              description: 수정일시
          description: 응답 데이터
        message:
          type: string
          description: 메시지
        status:
          type: string
          description: 결과 상태
    posts2009334939:
      required:
      - data
      - message
      - status
      type: object
      properties:
        data:
          type: array
          description: 응답 데이터
          items:
            required:
            - author
            - content
            - createdAt
            - id
            - title
            - updatedAt
            type: object
            properties:
              createdAt:
                type: string
                description: 생성일시
              author:
                type: string
                description: 작성자명
              id:
                type: number
                description: 게시글 ID
              title:
                type: string
                description: 제목
              content:
                type: string
                description: 내용
              updatedAt:
                type: string
                description: 수정일시
        message:
          type: string
          description: 메시지
        status:
          type: string
          description: 결과 상태
